version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: pet_adoption_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pet_adoption_db
      MYSQL_USER: petadoption
      MYSQL_PASSWORD: petpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - pet_adoption_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pet_adoption_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: pet_adoption_db
      DB_USER: petadoption
      DB_PASSWORD: petpassword
      JWT_SECRET: your_super_secret_jwt_key_for_production
      JWT_EXPIRES_IN: 7d
      PORT: 5000
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mysql
    networks:
      - pet_adoption_network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pet_adoption_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pet_adoption_network

volumes:
  mysql_data:

networks:
  pet_adoption_network:
    driver: bridge
